require("plugins.lazy")
require("plugins.plugins")
require("plugins.comments")
require("plugins.treesitter")
require("plugins.conform")
require("plugins.toggleterm")
vim.cmd("set rtp^=\"\'\"$(opam config var ocp-indent:share)")
